import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import HamburgerNavigation from '@components/HamburgerNavigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <HamburgerNavigation/>
        <footer className={inter.className}>
          <h4>Portfolio created with NextJS and Typescript</h4>
          <br />
          <h5>Social Links:</h5>
          <p>LinkedIn | YouTube | Artstation</p>
        </footer>
      </body>
    </html>
  )
}
